export const consoleHtml = String.raw`<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Muse Console</title>
<style>
:root{font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}body{margin:0;background:#f5f6f8;color:#15171a}main{max-width:760px;margin:0 auto;padding:18px}header{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:18px}h1{margin:0;font-size:24px}button,input,textarea,select{font:inherit}button{border:0;border-radius:10px;padding:12px 16px;cursor:pointer}.primary{background:#15171a;color:white}.secondary{background:white;border:1px solid #d8dbe0}.card{background:white;border:1px solid #e0e3e8;border-radius:14px;padding:16px;margin-bottom:14px;box-shadow:0 1px 2px rgba(0,0,0,.04)}label{display:block;font-weight:650;margin:12px 0 7px}input,textarea,select{width:100%;box-sizing:border-box;border:1px solid #cfd3d8;border-radius:10px;padding:12px;background:white}textarea{min-height:210px;resize:vertical;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:13px}.row{display:flex;gap:10px;align-items:center}.row>*{flex:1}.status{font-size:20px;font-weight:800}.status.PASS{color:#18794e}.status.FAIL{color:#b42318}.status.BLOCKED,.status.UNPROVEN{color:#a15c00}.muted{color:#69717c;font-size:13px}.hidden{display:none!important}.phase{padding:10px 0;border-bottom:1px solid #eceef1}.phase:last-child{border-bottom:0}.downloads{display:flex;flex-wrap:wrap;gap:10px;margin-top:14px}#error{color:#b42318;white-space:pre-wrap}
</style></head>
<body><main>
<header><h1>Muse</h1><div class="row" style="min-width:180px;max-width:360px;justify-content:flex-end"><span id="identityBadge" class="muted hidden" style="font-weight:700"></span><button id="newTest" class="secondary">New test</button><select id="history"><option value="">History</option></select></div></header>

<section id="identity" class="card hidden"><label for="name">Your name</label><input id="name" placeholder="Enter your name" autocomplete="name" value=""><button id="saveName" class="primary" style="margin-top:10px">Continue</button><div class="muted" style="margin-top:8px">Your name and test history stay in this browser. There is no user database in this MVP.</div></section>

<section id="form" class="card hidden"><label for="targetUrl">Test URL</label><input id="targetUrl" type="url" placeholder="https://example.com"><label for="mission">What should I test?</label><textarea id="mission" placeholder="Paste the Muse mission JSON produced by ChatGPT here. You do not need to understand the JSON."></textarea><div class="muted">The URL above is authoritative. Muse will replace the first navigate step with it.</div><button id="run" class="primary" style="margin-top:14px;width:100%">Run test</button><div id="error" style="margin-top:12px"></div></section>

<section id="result" class="card hidden"><div id="status" class="status"></div><p id="diagnosis"></p><div class="downloads"><button id="downloadHtml" class="primary">Download human report</button><button id="downloadJson" class="secondary">Download JSON</button></div><div class="muted" style="margin-top:10px">The human report contains the evidence and screenshots and works offline.</div></section>
</main>
<script>
(function(){
var state={report:null},identity=localStorage.getItem("muse.console.name"),identityEl=document.getElementById("identity"),formEl=document.getElementById("form"),resultEl=document.getElementById("result"),errorEl=document.getElementById("error"),identityBadge=document.getElementById("identityBadge");
function showApp(){identityEl.classList.add("hidden");formEl.classList.remove("hidden");if(identity){identityBadge.textContent=identity.length>1?identity:"S";identityBadge.classList.remove("hidden")}document.getElementById("targetUrl").focus()}
if(!identity)identityEl.classList.remove("hidden");else showApp();
document.getElementById("saveName").onclick=function(){var name=document.getElementById("name").value.trim();if(!name){errorEl.textContent="Please enter your name.";return}identity=name;localStorage.setItem("muse.console.name",name);showApp()};
function historyLoad(){var select=document.getElementById("history");while(select.options.length>1)select.remove(1);var history=JSON.parse(localStorage.getItem("muse.console.history")||"[]");history.forEach(function(item,index){var option=document.createElement("option");option.value=String(index);option.textContent=item.status+" — "+item.title;select.appendChild(option)})}
function historySave(report){var history=JSON.parse(localStorage.getItem("muse.console.history")||"[]");history.unshift({id:Date.now(),status:report.status,title:report.title||report.finalUrl||"Muse test",url:report.finalUrl||"",time:new Date().toISOString()});localStorage.setItem("muse.console.history",JSON.stringify(history.slice(0,30)));historyLoad()}
historyLoad();
document.getElementById("newTest").onclick=function(){state={report:null};document.getElementById("targetUrl").value="";document.getElementById("mission").value="";errorEl.textContent="";resultEl.classList.add("hidden");formEl.classList.remove("hidden");window.scrollTo(0,0)};
document.getElementById("history").onchange=function(event){var index=event.target.value;if(index==="")return;var history=JSON.parse(localStorage.getItem("muse.console.history")||"[]"),item=history[Number(index)];if(item){document.getElementById("targetUrl").value=item.url||"";errorEl.textContent="History is local and currently stores an index only. Re-run the saved mission to create a fresh downloadable report.";window.scrollTo(0,0)}event.target.value=""};
document.getElementById("run").onclick=async function(){errorEl.textContent="";resultEl.classList.add("hidden");document.getElementById("run").disabled=true;document.getElementById("run").textContent="Running…";try{var response=await fetch("/api/run",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({targetUrl:document.getElementById("targetUrl").value,mission:document.getElementById("mission").value})}),data=await response.json();if(!response.ok)throw new Error(data.error||"Test failed to start");state.report=data;document.getElementById("status").textContent=data.status;document.getElementById("status").className="status "+data.status;document.getElementById("diagnosis").textContent=(data.diagnosis&&data.diagnosis.summary?data.diagnosis.summary:"Test completed.")+(data.diagnosis&&data.diagnosis.nextAction?" "+data.diagnosis.nextAction:"");resultEl.classList.remove("hidden");historySave(data);window.scrollTo(0,document.body.scrollHeight)}catch(error){errorEl.textContent=error.message}finally{document.getElementById("run").disabled=false;document.getElementById("run").textContent="Run test"}};
function download(name,text,type){var blob=new Blob([text],{type:type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(url)},1000)}
function escapeHtml(value){return String(value==null?"":value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
function humanReport(report){var lines=["MUSE TEST REPORT","================","Status: "+report.status,"Objective: "+report.objective,"Final URL: "+(report.finalUrl||"n/a"),"Title: "+(report.title||"n/a"),"","DIAGNOSIS",report.diagnosis?report.diagnosis.summary:"n/a"];if(report.diagnosis&&report.diagnosis.nextAction)lines.push("Next action: "+report.diagnosis.nextAction);lines.push("","ACCEPTANCE CRITERIA");(report.acceptanceCriteria||[]).forEach(function(item,i){lines.push((i+1)+". "+item)});lines.push("","FINDINGS");(report.findings||[]).forEach(function(item){lines.push("["+item.severity.toUpperCase()+"] "+item.message);if(item.probableCause)lines.push("Cause: "+item.probableCause);if(item.recommendedAction)lines.push("Action: "+item.recommendedAction)});lines.push("","EVIDENCE");(report.evidence||[]).forEach(function(item,i){if(item.type==="navigation")lines.push((i+1)+". Navigated to "+item.url+" — "+item.title);if(item.type==="snapshot")lines.push((i+1)+". Page snapshot at "+item.url+": "+item.text.slice(0,3000));if(item.type==="action")lines.push((i+1)+". "+item.action+" at "+item.url);if(item.type==="screenshot")lines.push((i+1)+". Screenshot captured at "+item.url)});lines.push("","BUDGET",JSON.stringify(report.budget,null,2));return lines.join("\\n")}
document.getElementById("downloadJson").onclick=function(){if(state.report)download("muse-report-"+Date.now()+".json",JSON.stringify(state.report,null,2),"application/json")};
document.getElementById("downloadHtml").onclick=function(){if(!state.report)return;var report=state.report,body="<h1>Muse Test Report</h1><h2>Status: "+escapeHtml(report.status)+"</h2><p><strong>Objective:</strong> "+escapeHtml(report.objective)+"</p><p><strong>Final URL:</strong> "+escapeHtml(report.finalUrl||"n/a")+"</p><h2>Diagnosis</h2><p>"+escapeHtml(report.diagnosis?report.diagnosis.summary:"n/a")+"</p><h2>Findings</h2><pre>"+escapeHtml(JSON.stringify(report.findings||[],null,2))+"</pre><h2>Evidence</h2><pre>"+escapeHtml(humanReport(report))+"</pre>";(report.evidence||[]).forEach(function(item){if(item.type==="screenshot"&&item.data)body+="<h3>Screenshot</h3><img style='max-width:100%;border:1px solid #ddd' src='data:"+escapeHtml(item.mimeType||"image/jpeg")+";base64,"+item.data+"'>"});var html="<!doctype html><html><head><meta charset='utf-8'><title>Muse Test Report</title><style>body{font-family:system-ui;max-width:900px;margin:30px auto;padding:0 18px;line-height:1.5}pre{white-space:pre-wrap;background:#f5f5f5;padding:12px;border-radius:8px}img{margin:8px 0}</style></head><body>"+body+"</body></html>";download("muse-report-"+Date.now()+".html",html,"text/html")}
})();
</script></body></html>`;